#!/usr/bin/env bash

set -e

TOOL_SOURCE="${BASH_SOURCE[0]}"
while [ -h "$TOOL_SOURCE" ] ; do TOOL_SOURCE="$(readlink "$TOOL_SOURCE")"; done
SDLC_DIR="$( cd -P "$( dirname "$TOOL_SOURCE" )" && pwd )"
PRJ_HOME="$( cd -P "$( dirname "$SDLC_DIR" )" && pwd )"

BIN_DIR="${PRJ_HOME}/bin"
[[ -d "$BIN_DIR" ]] && rm -r "$BIN_DIR"

BUILD_DIR="${PRJ_HOME}/build"
[[ -d "$BUILD_DIR" ]] && rm -r "$BUILD_DIR"

DIST_DIR="${PRJ_HOME}/dist"
[[ -d "$DIST_DIR" ]] && rm -r "$DIST_DIR"
