#!/usr/bin/env bash

set -e

tool_source="${BASH_SOURCE[0]}"
while [ -h "$tool_source" ] ; do tool_source="$(readlink "$tool_source")"; done
project_scripts_dir="$( cd -P "$( dirname "$tool_source" )" && pwd )"
project_home="$( cd -P "$( dirname "$project_scripts_dir" )" && pwd )"

source "${project_scripts_dir}/config"

[[ -z "$GH_TOKEN" ]] && {
    echo "Missing GH_TOKEN"
    exit 1
}
docs_dir="${project_home}/docs"
cd "$docs_dir"

website_build_dir="${project_home}/build/website"
mkdir -p "$website_build_dir"

cp -r "$docs_dir" /documents

# Asciidoctor attributes
ci_ns="${REPO_OWNER}/${REPO_NAME}"
ci_build_id="$CI_BUILD_ID"
project_authors="${REPO_NAME} contributors"
echo "Using attributes ci-ns=${ci_ns} ci-build-id=${ci_build_id} project-authors=${project_authors}"

asciidoctor --doctype book \
            --attribute "project-version=${APP_VERSION}" \
            --attribute "project-authors=${project_authors}" \
            --attribute "ci-ns=${ci_ns}" \
            --attribute "ci-build-id=${ci_build_id}" \
            --destination-dir "$website_build_dir" \
            index.adoc

asciidoctor-pdf --doctype book \
                --attribute "project-version=${APP_VERSION}" \
                --attribute "project-authors=${project_authors}" \
                --attribute "ci-ns=${ci_ns}" \
                --attribute "ci-build-id=${ci_build_id}" \
                --destination-dir "${website_build_dir}/pdf" \
                --out-file="${REPO_NAME}_manual.pdf" \
                index.adoc
