name: CI Linux Mac

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    #if: "!contains(github.event.head_commit.message, '[skip ci]')"
    #container: 'golang:1.13'
    steps:
    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    # - name: Prepare container
    #   run: |
    #     apt-get install git
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      run: |
        .sdlc/build
        .sdlc/check
